---
  version: '3.8'
  services:
    fas_landing:
      image: nginx:latest
      container_name: fas-landing
      restart: unless-stopped
      env_file:
        - .env
      volumes:
        - ./lib:/opt/fas-scripts:ro 
        - ../web/dist:/usr/share/nginx/html
      ports:
        - '8081:80'
